### ISSUE TITLE
pretrained models are empty

### ISSUE THREAD

**Issue by evinhas** [Microsoft/ELL-models#69]
Hi, I am trying to use the pretrained models, such as it is stored in the following link

https://github.com/Microsoft/ELL-models/raw/master/models/ILSVRC2012/d_I224x224x3CMCMCMCMCMCMC1AS/d_I224x224x3CMCMCMCMCMCMC1AS.ell.zip

(Note: this is copied from tutorial https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/ )

But any of the downloaded zip files are corrupted, and the unzip command fails.

Please, could you check?

Thanks in advance.

**Comment by byronChanguion** [comment]
I checked the link above and it points to a 32MB zip file which extracted to a 95MB file called d_I224x224x3CMCMCMCMCMCMC1AS.ell, so this is working.
I think you may have run into a temporary problem we had with our GitHub quota.
Can you try again and let me know if it works?

**Comment by evinhas** [comment]
Sure, you are right. I've just downloaded the zip file, with the size you comented (32MB) and extracted it without issues. I can't check the model as I am at office just now, but I will use as soon as come home.

Thanks for supporting!
