### ISSUE TITLE
Only getting a 2.86 meg ZIp file.  inside model files are 129 bytes.

### ISSUE THREAD

**Issue by dpgindler** [microsoft/ELL-models#77]
I can get see a proper featurizer.ell.zip file.   unzip or open says damaged file.
I used unblock on the outer zip.  other files are text files are fine.
seems to be the case for all models, but only checked Cinnamon and Dulse.

Is this a problem on your end like issue #69 ..  or something I am doing.

I went to the upper most level and did a ZIP download.

**Comment by lovettchris** [comment]
This might be a git LFS issue.  Can you provide a link to which featurizer you are downloading exactly?  If you are using "curl" to download the file you have to add "--location" on the command line so that "curl" can traverse an HTTP redirect that github does, like this:
```
curl -O --location https://github.com/microsoft/ELL-models/raw/master/models/speech_commands_v0.01/Cinnamon/featurizer.ell.zip
```

**Comment by dpgindler** [comment]
I went to this link:    https://github.com/Microsoft/ELL-models
click on the green button then selected download zip.   basically downloading it all.
i then open the zip and looked at all the models.

**Comment by lovettchris** [comment]
I see that would be a big zip file, I've never tried that.  If the featurizer inside this zip is bad this might be a github bug, or perhaps download zip doesn't work for "git lfs" repos.  But I always use git clone on this repo, then you can get the models that way.

**Comment by dpgindler** [comment]
i used git clone in a git bash window and get the same result.

**Comment by lovettchris** [comment]
Can you try my "curl" solution above?  You might also need to [install git lfs](https://github.com/git-lfs/git-lfs/wiki/Installation) if you have not already.

**Comment by dpgindler** [comment]
I had a coworker run the git command and his command is still running with getting over 5 gig.

i do not have git lfs and maybe he does...  checking...

**Comment by dpgindler** [comment]
yes..    LFS must be installed.   Closing issue.
